// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TirelireShop;

namespace TirelireShop.Migrations
{
    [DbContext(typeof(DBTirelireShopContext))]
    [Migration("20200818141504_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("TirelireShop.Avis", b =>
                {
                    b.Property<int>("Idavis")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDavis")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnName("contenu")
                        .HasColumnType("text");

                    b.Property<string>("Idclient")
                        .HasColumnName("IDclient")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Idproduit")
                        .HasColumnName("IDproduit")
                        .HasColumnType("int");

                    b.Property<bool>("Statut")
                        .HasColumnName("statut")
                        .HasColumnType("bit");

                    b.HasKey("Idavis");

                    b.HasIndex("Idclient");

                    b.HasIndex("Idproduit");

                    b.ToTable("Avis");
                });

            modelBuilder.Entity("TirelireShop.Client", b =>
                {
                    b.Property<string>("Idclient")
                        .HasColumnName("IDclient")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnName("nom")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnName("prenom")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("StatutCompte")
                        .HasColumnName("statutCompte")
                        .HasColumnType("bit");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Idclient");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("TirelireShop.Commande", b =>
                {
                    b.Property<int>("Idcommande")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDcommande")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnName("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Idclient")
                        .HasColumnName("IDclient")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdstatutCommande")
                        .HasColumnName("IDstatutCommande")
                        .HasColumnType("int");

                    b.HasKey("Idcommande");

                    b.HasIndex("Idclient");

                    b.HasIndex("IdstatutCommande");

                    b.ToTable("Commande");
                });

            modelBuilder.Entity("TirelireShop.Couleur", b =>
                {
                    b.Property<int>("Idcouleur")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDcouleur")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Couleur1")
                        .IsRequired()
                        .HasColumnName("couleur")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Idcouleur");

                    b.ToTable("Couleur");
                });

            modelBuilder.Entity("TirelireShop.DetailsCommande", b =>
                {
                    b.Property<int>("IddetailsCommande")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDdetailsCommande")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Idcommande")
                        .HasColumnName("IDcommande")
                        .HasColumnType("int");

                    b.Property<int>("Idproduit")
                        .HasColumnName("IDproduit")
                        .HasColumnType("int");

                    b.Property<decimal>("Prix")
                        .HasColumnName("prix")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Quantite")
                        .HasColumnName("quantite")
                        .HasColumnType("int");

                    b.HasKey("IddetailsCommande");

                    b.HasIndex("Idcommande");

                    b.HasIndex("Idproduit");

                    b.ToTable("DetailsCommande");
                });

            modelBuilder.Entity("TirelireShop.Fabricant", b =>
                {
                    b.Property<int>("Idfabricant")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDfabricant")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnName("adresse")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnName("nom")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Idfabricant");

                    b.ToTable("Fabricant");
                });

            modelBuilder.Entity("TirelireShop.Image", b =>
                {
                    b.Property<int>("Idimage")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDimage")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CheminAcces")
                        .IsRequired()
                        .HasColumnName("cheminAcces")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Idproduit")
                        .HasColumnName("IDproduit")
                        .HasColumnType("int");

                    b.HasKey("Idimage");

                    b.HasIndex("Idproduit");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("TirelireShop.Produit", b =>
                {
                    b.Property<int>("Idproduit")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDproduit")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Capacite")
                        .HasColumnName("capacite")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionFabricant")
                        .IsRequired()
                        .HasColumnName("descriptionFabricant")
                        .HasColumnType("text");

                    b.Property<decimal>("Hauteur")
                        .HasColumnName("hauteur")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Idcouleur")
                        .HasColumnName("IDcouleur")
                        .HasColumnType("int");

                    b.Property<int>("Idfabricant")
                        .HasColumnName("IDfabricant")
                        .HasColumnType("int");

                    b.Property<int>("Idimage")
                        .HasColumnName("IDimage")
                        .HasColumnType("int");

                    b.Property<decimal>("Largeur")
                        .HasColumnName("largeur")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Longueur")
                        .HasColumnName("longueur")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnName("nom")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal>("Poids")
                        .HasColumnName("poids")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Prix")
                        .HasColumnName("prix")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("StatutActivation")
                        .HasColumnName("statutActivation")
                        .HasColumnType("bit");

                    b.HasKey("Idproduit");

                    b.HasIndex("Idcouleur");

                    b.HasIndex("Idfabricant");

                    b.ToTable("Produit");
                });

            modelBuilder.Entity("TirelireShop.StatutCommande", b =>
                {
                    b.Property<int>("IdstatutCommande")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IDstatutCommande")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StatutCommande1")
                        .IsRequired()
                        .HasColumnName("statutCommande")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("IdstatutCommande");

                    b.ToTable("StatutCommande");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TirelireShop.Client", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TirelireShop.Client", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TirelireShop.Client", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TirelireShop.Client", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TirelireShop.Avis", b =>
                {
                    b.HasOne("TirelireShop.Client", "IdclientNavigation")
                        .WithMany("Avis")
                        .HasForeignKey("Idclient")
                        .HasConstraintName("FK_Avis_Client");

                    b.HasOne("TirelireShop.Produit", "IdproduitNavigation")
                        .WithMany("Avis")
                        .HasForeignKey("Idproduit")
                        .HasConstraintName("FK_Avis_Produit")
                        .IsRequired();
                });

            modelBuilder.Entity("TirelireShop.Commande", b =>
                {
                    b.HasOne("TirelireShop.Client", "IdclientNavigation")
                        .WithMany("Commande")
                        .HasForeignKey("Idclient")
                        .HasConstraintName("FK_Commande_Client");

                    b.HasOne("TirelireShop.StatutCommande", "IdstatutCommandeNavigation")
                        .WithMany("Commande")
                        .HasForeignKey("IdstatutCommande")
                        .HasConstraintName("FK_Commande_StatutCommande")
                        .IsRequired();
                });

            modelBuilder.Entity("TirelireShop.DetailsCommande", b =>
                {
                    b.HasOne("TirelireShop.Commande", "IdcommandeNavigation")
                        .WithMany("DetailsCommande")
                        .HasForeignKey("Idcommande")
                        .HasConstraintName("FK_DetailsCommande_Commande")
                        .IsRequired();

                    b.HasOne("TirelireShop.Produit", "IdproduitNavigation")
                        .WithMany("DetailsCommande")
                        .HasForeignKey("Idproduit")
                        .HasConstraintName("FK_DetailsCommande_Produit")
                        .IsRequired();
                });

            modelBuilder.Entity("TirelireShop.Image", b =>
                {
                    b.HasOne("TirelireShop.Produit", "IdproduitNavigation")
                        .WithMany("Image")
                        .HasForeignKey("Idproduit")
                        .HasConstraintName("FK_Image_Produit")
                        .IsRequired();
                });

            modelBuilder.Entity("TirelireShop.Produit", b =>
                {
                    b.HasOne("TirelireShop.Couleur", "IdcouleurNavigation")
                        .WithMany("Produit")
                        .HasForeignKey("Idcouleur")
                        .HasConstraintName("FK_Produit_Couleur")
                        .IsRequired();

                    b.HasOne("TirelireShop.Fabricant", "IdfabricantNavigation")
                        .WithMany("Produit")
                        .HasForeignKey("Idfabricant")
                        .HasConstraintName("FK_Produit_Fabricant")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
